version: "3.8"

services:
  jupyter:
    container_name: my_jupyter_container
    build: .
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
